### ISSUE TITLE
some "indices" to add to `Demographic Information / Neighborhood Characteristics` table

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/geomarkers#5]
- [ ] https://www.atsdr.cdc.gov/placeandhealth/svi/index.html
- [ ] https://www.neighborhoodatlas.medicine.wisc.edu/
- [ ] https://www.graham-center.org/rgc/maps-data-tools/sdi/social-deprivation-index.html
- [ ] https://www.census.gov/data/experimental-data-products/community-resilience-estimates.html

**Comment by andrew-vancil** [comment]
I've added rows for each of these. One of the presenters today also linked to this group of environmental datasets: https://sites.wustl.edu/acag/datasets/ . Think this would be worth adding?

**Comment by cole-brokamp** [comment]
thanks, yeah this would be great to add
